name: poke_demo
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
